<?php

namespace App\Database\Seeds\Development;

use CodeIgniter\Database\Seeder;

class Languages extends Seeder
{
	public function run()
	{

		$data = [
			'name'    		=>  'English',
			'short_form'    		=>  'en',
			'language_code'    		=>  'en-US',
			'text_direction'    		=>  'ltr',
			'text_editor_lang'    		=>  'id',
			'status'    		=>  1,
			'language_order'    		=>  1

		];

		$this->db->table('languages')->insert($data);

		// Translations Form my Database
		$this->db->query($this->translations());
	}

	public function translations()
	{
		/** 
		 * SQL FROM MY DATABASE
		 * 27-01-2022 Las Update
		 */

		$sql = "INSERT INTO `language_translations` (`id`, `lang_id`, `label`, `translation`) VALUES
		(1, 1, 'form_email', 'Email'),
		(2, 1, 'form_password', 'Password'),
		(3, 1, 'login_error', 'Wrong username or password!'),
		(4, 1, 'message_ban_error', 'Your account has been banned!'),
		(5, 1, 'login', 'Login'),
		(6, 1, 'connect-with', 'Connect With'),
		(7, 1, 'connect_with_facebook', 'Sign in using Facebook'),
		(8, 1, 'connect_with_google', 'Sign in using Google'),
		(9, 1, 'forgot_password', 'Forgot Password'),
		(10, 1, 'register_new_membership', 'Register a new membership'),
		(11, 1, 'remember_me', 'Remember Me'),
		(12, 1, 'form_confirm_password', 'Retype Password'),
		(13, 1, 'form_username', 'Username'),
		(14, 1, 'msg_username_unique_error', 'The username has already been taken.'),
		(15, 1, 'message_email_unique_error', 'The email has already been taken.'),
		(16, 1, 'msg_send_confirmation_email', 'A confirmation email has been sent to your email address for activation. Please confirm your account.'),
		(17, 1, 'msg_register_success', 'Register Success Please Login'),
		(18, 1, 'message_register_error', 'There was a problem during registration. Please try again!'),
		(19, 1, 'msg_recaptcha', 'Please confirm that you are not a robot!'),
		(20, 1, 'register', 'Register'),
		(21, 1, 'edit_translations', 'Edit Translations'),
		(22, 1, 'language', 'Language'),
		(23, 1, 'active', 'Active'),
		(24, 1, 'inactive', 'Inactive'),
		(25, 1, 'enable', 'Enable'),
		(26, 1, 'disable', 'Disable'),
		(27, 1, 'option', 'Option'),
		(28, 1, 'options', 'Options'),
		(29, 1, 'language_settings', 'Language Settings'),
		(30, 1, 'id', 'ID'),
		(31, 1, 'language_name', 'Language Name'),
		(32, 1, 'translation', 'Translation'),
		(33, 1, 'language_code', 'Language Code'),
		(34, 1, 'language_shortname', 'Language Shortname'),
		(35, 1, 'status', 'Status'),
		(36, 1, 'language_order', 'Order'),
		(37, 1, 'add_language', 'Add Language'),
		(38, 1, 'languages', 'Languages'),
		(39, 1, 'select_an_option', 'Select Options'),
		(40, 1, 'edit', 'Edit'),
		(41, 1, 'delete', 'Delete'),
		(42, 1, 'default_language', 'Default Language'),
		(43, 1, 'save_changes', 'Save Changes'),
		(44, 1, 'save', 'Save'),
		(45, 1, 'text_editor_language', 'Text Editor Language'),
		(46, 1, 'text_direction', 'Text Direction'),
		(47, 1, 'left_to_right', 'Left to Rght'),
		(48, 1, 'right_to_left', 'Right to Left'),
		(49, 1, 'filter', 'Filter'),
		(50, 1, 'search', 'Search'),
		(51, 1, 'show', 'Show'),
		(52, 1, 'phrase', 'Pharse'),
		(53, 1, 'label', 'Label'),
		(54, 1, 'msg_updated', 'Changes successfully saved!'),
		(55, 1, 'msg_suc_updated', 'successfully updated'),
		(56, 1, 'msg_error', 'An error occurred please try again!'),
		(57, 1, 'msg_suc_added', 'successfully added!'),
		(58, 1, 'update_language', 'Update Language'),
		(59, 1, 'msg_language_delete', 'Default language cannot be deleted!'),
		(60, 1, 'msg_suc_deleted', 'successfully deleted!'),
		(61, 1, 'short_form', 'Short Forms'),
		(62, 1, 'users', 'Users'),
		(63, 1, 'add_user', 'Add User'),
		(64, 1, 'administrators', 'Administrators'),
		(65, 1, 'msg_user_added', 'User successfully added!'),
		(66, 1, 'msg_role_changed', 'User role successfully changed!'),
		(67, 1, 'username', 'Username'),
		(68, 1, 'email', 'Email'),
		(69, 1, 'role', 'Role'),
		(70, 1, 'update_profile', 'Update Profile'),
		(71, 1, 'msg_slug_used', 'The slug you entered is being used by another user!'),
		(72, 1, 'change_avatar', 'Change Avatar'),
		(73, 1, 'social_accounts', 'Social Accounts'),
		(74, 1, 'about_me', 'About Me'),
		(75, 1, 'slug', 'Slug'),
		(76, 1, 'url', 'Url'),
		(77, 1, 'email_status', 'Email Status'),
		(78, 1, 'banned', 'Banned'),
		(79, 1, 'all', 'All'),
		(80, 1, 'confirmed', 'Confirmed'),
		(81, 1, 'unconfirmed', 'Unconfirmed'),
		(82, 1, 'date', 'Date'),
		(83, 1, 'change_user_role', 'Change Role'),
		(84, 1, 'confirm_user_email', 'Confirm email'),
		(85, 1, 'ban_user', 'Ban User'),
		(86, 1, 'remove_ban', 'Remove Ban'),
		(87, 1, 'no_records_found', 'No records found.'),
		(88, 1, 'avatar', 'Avatar'),
		(89, 1, 'image', 'Image'),
		(90, 1, 'ok', 'Ok'),
		(91, 1, 'cancel', 'Cancel'),
		(92, 1, 'confirm_ban', 'Are you sure you want to ban this user?'),
		(93, 1, 'confirm_remove_ban', 'Are you sure you want to remove ban for this user?'),
		(94, 1, 'confirm_user', 'Are you sure you want to delete this user?'),
		(95, 1, 'close', 'Close'),
		(96, 1, 'roles_permissions', 'Roles & Permissions'),
		(97, 1, 'edit_role', 'Edit Role'),
		(98, 1, 'permissions', 'Permissions'),
		(99, 1, 'all_permissions', 'All Permissions'),
		(100, 1, 'admin_panel', 'Admin Panel'),
		(101, 1, 'settings', 'Settings'),
		(102, 1, 'role_name', 'Role Name'),
		(103, 1, 'login_dsc', 'Enter your email address and password to access account.'),
		(104, 1, 'preferences', 'Preferences'),
		(105, 1, 'route_settings', 'Route Settings'),
		(106, 1, 'email_settings', 'Email Settings'),
		(107, 1, 'visual_settings', 'Visual Settings'),
		(108, 1, 'general_settings', 'General Settings'),
		(109, 1, 'social_media_settings', 'Social Media Settings'),
		(110, 1, 'maintenance_mode', 'Maintenance Mode'),
		(111, 1, 'google_recaptcha', 'Google Recaptcha'),
		(112, 1, 'timezone', 'Timezone'),
		(113, 1, 'cookie_prefix', 'Cookie Prefix'),
		(114, 1, 'app_name', 'Application Name'),
		(115, 1, 'copyright', 'Copyright'),
		(116, 1, 'site_key', 'Site Key'),
		(117, 1, 'secret_key', 'Secret Key'),
		(118, 1, 'title', 'Title'),
		(119, 1, 'description', 'Description'),
		(120, 1, 'maintenance', 'Maintenance'),
		(121, 1, 'logo', 'Logo'),
		(122, 1, 'change_logo', 'Change Logo'),
		(123, 1, 'logo_dark', 'Logo Dark'),
		(124, 1, 'logo_email', 'Logo Email'),
		(125, 1, 'favicon', 'Favicon'),
		(126, 1, 'change', 'Change'),
		(127, 1, 'index', 'Dashboard'),
		(128, 1, 'admin', 'Admin'),
		(129, 1, 'logout', 'Logout'),
		(130, 1, 'contact_messages', 'Contact Message'),
		(131, 1, 'send_contact_to_mail', 'Send Contact To Email'),
		(132, 1, 'contact_messages_will_send', 'Contact Messages Will Send'),
		(133, 1, 'yes', 'yes'),
		(134, 1, 'no', 'No'),
		(135, 1, 'mail_library', 'Mail Library'),
		(136, 1, 'mail_protocol', 'Mail Protocol'),
		(137, 1, 'mail_title', 'Mail title'),
		(138, 1, 'mail_host', 'Mail Host'),
		(139, 1, 'mail_port', 'Mail Port'),
		(140, 1, 'mail_username', 'Mail Username'),
		(141, 1, 'mail_password', 'Mail Password'),
		(142, 1, 'email_template', 'Email Template'),
		(143, 1, 'email_verification', 'Email Verification'),
		(144, 1, 'send_test_email', 'Send Test Email'),
		(145, 1, 'send_test_email_exp', 'You can send a test mail to check if your mail server is working.'),
		(146, 1, 'send_email', 'Send Email'),
		(147, 1, 'smtp', 'SMTP'),
		(148, 1, 'mail', 'Mail'),
		(149, 1, 'change_password', 'Change Password'),
		(150, 1, 'delete_account', 'Delete Account'),
		(151, 1, 'resend_activation_email', 'Resend Activation Email'),
		(152, 1, 'profile', 'Profile'),
		(153, 1, 'form_old_password', 'Type Old Password'),
		(154, 1, 'delete_account_confirm', 'After the account is deleted, the data will not be able to be restored, are you sure?'),
		(155, 1, 'reset_password', 'Reset Password'),
		(156, 1, 'enter_email_address', 'Enter Email Address'),
		(157, 1, 'enter_new_password', 'Enter New Password'),
		(158, 1, 'msg_email_sent', 'Email successfully sent!'),
		(159, 1, 'encryption', 'Encryption'),
		(160, 1, 'reply_to', 'Reply-To'),
		(161, 1, 'address', 'Address'),
		(162, 1, 'phone', 'Phone'),
		(163, 1, 'contact_text', 'Contact Text'),
		(164, 1, 'contact_settings', 'Contact Settings'),
		(165, 1, 'confirm_your_email', 'Confirm Your Email'),
		(166, 1, 'msg_confirmation_email', 'Please confirm your email address by clicking the button below.'),
		(167, 1, 'contact_message', 'Contact Message'),
		(168, 1, 'email_reset_password', 'Please click on the button below to reset your password.'),
		(169, 1, 'reset_password_error', 'We can\'t find a user with that e-mail address!'),
		(170, 1, 'reset_password_success', 'We\'ve sent an email for resetting your password to your email address. Please check your email for next steps.'),
		(171, 1, 'message_change_password_success', 'Your password has been successfully changed!'),
		(172, 1, 'message_change_password_error', 'There was a problem changing your password!'),
		(173, 1, 'msg_confirmed', 'Your email address has been successfully confirmed!'),
		(174, 1, 'msg_confirmed_required', 'Please verify your email address!'),
		(175, 1, 'btn_goto_home', 'Go Back to the Homepage'),
		(176, 1, 'social_login_configuration', 'Social Login Configuration'),
		(177, 1, 'configurations', 'Configurations'),
		(178, 1, 'facebook', 'Facebook'),
		(179, 1, 'app_id', 'App Id'),
		(180, 1, 'app_secret', 'App Secret'),
		(181, 1, 'google', 'Google'),
		(182, 1, 'client_id', 'Client Id'),
		(183, 1, 'client_secret', 'Client Secret'),
		(184, 1, 'social_login', 'Social Login'),
		(185, 1, 'minute', 'Minute'),
		(186, 1, 'minutes', 'minutes'),
		(187, 1, 'hour', 'Hour'),
		(188, 1, 'hours', 'Hours'),
		(189, 1, 'day', 'Day'),
		(190, 1, 'month', 'Month'),
		(191, 1, 'year', 'Year'),
		(192, 1, 'ago', 'Ago'),
		(193, 1, 'just_now', 'Just Now'),
		(194, 1, 'view', 'View'),
		(195, 1, 'views', 'Views'),
		(196, 1, 'select', 'Select'),
		(197, 1, 'selects', 'Selects'),
		(198, 1, 'fullname', 'Full Name'),
		(199, 1, 'mrmssmrs', 'Mr/Ms'),
		(200, 1, 'mr', 'Mr.'),
		(201, 1, 'ms', 'Ms.'),
		(202, 1, 'date_of_birth', 'Date Of Birth'),
		(203, 1, 'messages', 'Messages'),
		(204, 1, 'compose', 'Compose'),
		(205, 1, 'inbox', 'Inbox'),
		(206, 1, 'January', 'January'),
		(207, 1, 'February', 'February'),
		(208, 1, 'March', 'March'),
		(209, 1, 'May', 'May'),
		(210, 1, 'April', 'April'),
		(211, 1, 'June', 'June'),
		(212, 1, 'July', 'July'),
		(213, 1, 'August', 'August'),
		(214, 1, 'September', 'September'),
		(215, 1, 'October', 'October'),
		(216, 1, 'November', 'November'),
		(217, 1, 'December', 'December'),
		(218, 1, 'firstname', 'First Name'),
		(219, 1, 'lastname', 'Last Name'),
		(220, 1, 'gender', 'Gender'),
		(221, 1, 'male', 'Male'),
		(222, 1, 'female', 'Female'),
		(223, 1, 'please_select', 'Please select'),
		(224, 1, 'message', 'Message'),
		(225, 1, 'sent_item', 'Sent Item'),
		(226, 1, 'sent_items', 'Sent Items'),
		(227, 1, 'confirm_language', 'Are you sure you want to delete this language?'),
		(228, 1, 'add_translations', 'Add Translations'),
		(229, 1, 'msg_label_unique_error', 'The Label has already been on database'),
		(230, 1, 'dashboard', 'Dashboard'),
		(231, 1, 'name', 'Name'),
		(232, 1, 'mobile_no', 'Mobile Number'),
		(233, 1, 'contact_name', 'Contact Name'),
		(234, 1, 'contact_phone', 'Contact Phone'),
		(235, 1, 'contact_email', 'Contact email'),
		(236, 1, 'contact_address', 'Contact Address'),
		(237, 1, 'action', 'Action'),
		(238, 1, 'terms_and_conditions', 'Terms and Conditions'),
		(239, 1, 'form_validation_is_unique', 'The {field} field must contain a unique value.'),
		(240, 1, 'form_validation_matches', 'The {field} field does not match the {param} field.'),
		(241, 1, 'form_validation_max_length', 'The {field} field cannot exceed {param} characters in length.'),
		(242, 1, 'form_validation_min_length', 'The {field} field must be at least {param} characters in length.'),
		(243, 1, 'form_validation_required', 'The {field} field is required.'),
		(244, 1, 'browse_files', 'Browse Files'),
		(245, 1, 'reset', 'Reset'),
		(246, 1, 'drag_drop_files_here', 'Drag and drop files here or'),
		(247, 1, 'images', 'Images'),
		(248, 1, 'waiting', 'Waiting'),
		(249, 1, 'invalid_file_type', 'Invalid file type!'),
		(250, 1, 'auth_settings', 'Auth Setting'),
		(251, 1, 'registration_system', 'Registration System'),
		(252, 1, 'auth_background', 'Auth Background'),
		(253, 1, 'home', 'Home'),
		(254, 1, 'confirm_delete', 'Are you sure to remove this ? '),
		(255, 1, 'msg_error_row', 'Please delete the child data included in this data first!'),
		(256, 1, 'addon_informations', 'Addon informations'),
		(257, 1, 'pwa', 'PWA'),
		(258, 1, 'pwa_status', 'PWA Status'),
		(259, 1, 'message_unique_error', 'This data has already been registered'),
		(260, 1, 'location', 'Location'),
		(261, 1, 'locations', 'Locations'),
		(262, 1, 'country', 'Country'),
		(263, 1, 'country_id', 'Country ID'),
		(264, 1, 'state', 'State'),
		(265, 1, 'state_id', 'State ID'),
		(266, 1, 'city', 'City'),
		(267, 1, 'zip_code', 'Postal Code'),
		(268, 1, 'add', 'Add'),
		(269, 1, 'continent_code', 'Continent Code'),
		(270, 1, 'basic_informations', 'Basic Informations'),
		(271, 1, 'days', 'Days'),
		(272, 1, 'months', 'Months'),
		(273, 1, 'years', 'Years'),
		(274, 1, 'bank_account', 'Bank Account'),
		(275, 1, 'received', 'Received'),
		(276, 1, 'progress', 'Progress'),
		(277, 1, 'period', 'Period'),
		(278, 1, 'generate', 'Generate'),
		(279, 1, 'detail', 'Detail'),
		(280, 1, 'minimal', 'Minimal'),
		(281, 1, 'msg_user_banned', 'User successfully banned!'),
		(282, 1, 'msg_ban_removed', 'User ban successfully removed!'),
		(283, 1, 'add_role', 'Add Role'),
		(284, 1, 'wrong_password_error', 'Curent Password Wrong'),
		(285, 1, 'inactivate_all', 'Inactivate All'),
		(286, 1, 'activate_all', 'Activate All'),
		(287, 1, 'contact', 'Contact'),
		(288, 1, 'cache_system', 'Cache System'),
		(289, 1, 'refresh_cache_database_changes', 'Refresh Cache Database Changes'),
		(290, 1, 'cache_refresh_time', 'Cache Refresh Time'),
		(291, 1, 'cache_refresh_time_exp', 'After this time, your cache files will be refreshed.'),
		(292, 1, 'reset_cache', 'Reset Cache'),
		(293, 1, 'msg_reset_cache', 'All cache files have been deleted!'),
		(294, 1, 'address_information', 'Address Information'),
		(295, 1, 'payment_method', 'Payment Method'),
		(296, 1, 'menu_management', 'Menu Management'),
		(297, 1, 'menu_category', 'Menu Category'),
		(298, 1, 'menu_order', 'Menu Order'),
		(299, 1, 'menu', 'Menu'),
		(300, 1, 'menu_title', 'Title'),
		(301, 1, 'menu_url', 'Url'),
		(302, 1, 'icon', 'Icon'),
		(303, 1, 'submenu', 'Submenu'),
		(304, 1, 'menu_parent', 'Menu Parent'),
		(305, 1, 'submenu_title', 'Submenu Title'),
		(306, 1, 'submenu_url', 'Submenu URL'),
		(307, 1, 'need_translations_desc', 'You Need Added Translation On Menu Languages'),
		(308, 1, 'need_routes_desc', 'Better Register URL on Routes')";

		return $sql;
	}
}
